version: '3.4'

services:
  scraper_container:
    container_name: scraper_container
    image: chancewave/scraper:latest
    ports:
      - "9201:9201"
    depends_on:
      - mongodb_container

  mongodb_container:
    container_name: mongodb_container
    image : mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=CHANCEWAVE
      - MONGO_INITDB_ROOT_PASSWORD=MYSTERICO
    volumes:
      # - /home/ubuntu/scraping_data/mongodb:/data/db
      - C:/scraping_data/mongodb:/data/db
    ports:
      - "9202:27017"
    command: mongod --quiet --logpath /dev/null 
    depends_on:
      - message_broker_container
  
  message_broker_container:
    container_name: message_broker_container
    image: rabbitmq:3.9.9
    environment:
      - RABBITMQ_DEFAULT_USER=CHANCEWAVE
      - RABBITMQ_DEFAULT_PASS=MYSTERICO
    volumes:
        # - /home/ubuntu/scraping_data/rabbitmq/data/:/var/lib/rabbitmq/
        # - /home/ubuntu/scraping_data/rabbitmq/data/:/var/lib/rabbitmq/
        - C:/scraping_data/rabbitmq/data/:/var/lib/rabbitmq/
        - C:/scraping_data/rabbitmq/log/:/var/log/rabbitmq/
        - C:/workspace/chancewave-scraper/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

    ports:
      - "5672:5672"
      - "9203:15672"
    # command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]

  celery_container: 
    container_name: celery_container
    image: chancewave/scraper:latest
    command: celery -A workers.scraping_scheduler.scheduler worker --loglevel=info -P gevent --autoscale=24,6
    volumes:
      # - /home/ubuntu/scraping_data/celery/:/app/
      - C:/scraping_data/celery/:/app/

    depends_on:
      - scraper_container
      - mongodb_container
      - message_broker_container